name: ci
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - run: git config --global user.email "hatesegfault@protonmail.ch"
      - run: git config --global user.name "hatesegfault"
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: get-current
        run: |
          echo "::set-output name=current::$(./get_current)"
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: lovesegfault/hqplayerd:latest,lovesegfault/hqplayerd:${{ steps.get-current.outputs.current }}
